//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1.ServiceRef1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef1.WebServeSoap")]
    public interface WebServeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addkaro", ReplyAction="*")]
        int Addkaro(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addkaro", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddkaroAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServeSoapChannel : WebApp1.ServiceRef1.WebServeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServeSoapClient : System.ServiceModel.ClientBase<WebApp1.ServiceRef1.WebServeSoap>, WebApp1.ServiceRef1.WebServeSoap {
        
        public WebServeSoapClient() {
        }
        
        public WebServeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Addkaro(int a, int b) {
            return base.Channel.Addkaro(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddkaroAsync(int a, int b) {
            return base.Channel.AddkaroAsync(a, b);
        }
    }
}
